name "httpd"
maintainer "Luis Mu\u00F1iz"
maintainer_email "lmuniz@pue.es"
license "all_rights"
description "Installs/Configures httpd"
long_description "Installs/Configures httpd"
version "0.1.0"
source_url "https://github.com/chinocudeiro2/httpd.git"
issues_url "https://github.com/chinocudeiro2/httpd/issues"
